# https://github.com/mono0926/hugo-mono
baseurl = "https://mono0926.com"
languageCode = "ja"
title = "mono0926.com"
auther = "Masayuki Ono"
pygmentsStyle = "monokai"
theme = "hugo-mono"

[permalinks]
    post = ":section/:filename/"

[params]
    logo = "/images/love_logo.png"
    newSite = "https://mono0926.notion.site/mono-Masayuki-Ono-8959cd3bd40142e19ec433c5cd5b449b"
    copyright = "Masayuki Ono All right reserved."
    twitter = "https://twitter.com/_mono"
    facebook = "https://www.facebook.com/mono0926"
    github = "https://github.com/mono0926"
    email = "mono0926@gmail.com"
    wagePerHour = "20,000円/時"
    wagePerHourMinimum = "12,000円/時"
    wagePerHourPriorConsultation = "6,000円/時"
