# https://github.com/rakuishi/hugo-zen
baseurl = "http://mono0926.com"
languageCode = "ja"
title = "monoHub"
auther = "Masayuki Ono"
publishdir = "public"

[permalinks]
    post = "blog/:year/:month/:day/:filename/"