# https://github.com/mono0926/hugo-mono
baseurl = "http://mono0926.com"
languageCode = "ja"
title = "mono-log"
auther = "Masayuki Ono"
pygmentsStyle = "monokai"
theme = "hugo-mono"

[permalinks]
    post = ":section/:filename/"

[params]
    logo = "/images/love.png_logo"
    copyright = "Masayuki Ono All right reserved."
    twitter = "https://twitter.com/_mono"
    facebook = "https://www.facebook.com/mono0926"
    github = "https://github.com/mono0926"
    email = "mono0926@gmail.com"